export const SET_QUOTEDATA = "SET_QUOTEDATA";
export const SET_RANDOMINDEX = "SET_RANDOMINDEX";
export const SET_BAKGROUNDIMAGE = "SET_BAKGROUNDIMAGE";
export const SET_BACKGROUNDIMAGEARRAY = "SET_BACKGROUNDIMAGEARRAY";
export const SET_HIDEQUOTE = "SET_HIDEQUOTE";
export const SET_SHOWQUOTE = "SET_SHOWQUOTE";
